<?php

namespace AppBundle\Repository;

/**
 * DiscoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscoverRepository extends \Doctrine\ORM\EntityRepository
{
}
