<?php

namespace AppBundle\Repository;

/**
 * RecentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecentRepository extends \Doctrine\ORM\EntityRepository
{
}
